name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install zola
        run: |
          wget https://github.com/barnumbirr/zola-debian/releases/download/v0.17.2-1/zola_0.17.2-1_amd64_bullseye.deb
          sudo dpkg -i zola_0.17.2-1_amd64_bullseye.deb

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Init submodules
        run: npm run setup

      - name: Install dependencies
        run: CI=false npm ci

      - name: Lint code
        run: npm run lint

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
